# Default values for helium.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
labels:
  aadpodidbinding: owtraffic-mi #should be value of $MI_Name from the output of aad-podid.sh
  version: blue

image:
  repository: retaildevcrew #The specific acr created for this environment
  name: helium-csharp # The name of the image for the helium-csharp repo
  tag: beta

ingress:
  hosts:
    - 40.89.249.241.nip.io # Replace the IP address with the external IP of the Istio ingress gateway (value of $INGRESS_PIP or run kubectl get svc istio-ingressgateway -n istio-system to see the correct IP)
  paths: 
    - /

keyVaultName: owtraffic # Replace with the name of the Key Vault that holds the secrets