apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helium.fullname" . }}-green
  labels:
{{- toYaml .Values.labels | nindent 4 }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/name: {{ include "helium.name" . }}-green
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: green
  {{- with .Values.annotations }}
  annotations:
    rollme: {{ randAlphaNum 5 | quote }}
{{ toYaml . | indent 4 }}
      {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "helium.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
{{- toYaml .Values.labels | nindent 8 }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        app.kubernetes.io/name: {{ include "helium.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: {{ include "helium.name" . }}
        version: green
      {{- with .Values.annotations }}
      annotations:
{{ toYaml . | indent 8 }}
      {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "helium.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.greenimage.repository }}/{{ .Values.greenimage.name }}:{{ .Values.greenimage.tag }}"
          imagePullPolicy: {{ .Values.greenimage.pullPolicy }}
          env:
            - name: WEBSITE_ROLE_INSTANCE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KEYVAULT_NAME
              value: {{ .Values.keyVaultName }}
          ports:
            - name: http
              containerPort: 4120
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            failureThreshold: 1
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 120
            failureThreshold: 1
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
