{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "helium.serviceAccountName" . }}
  labels:
{{ include "helium.labels" . | indent 4 }}
{{- end -}}
