---
  apiVersion: config.istio.io/v1alpha2
  kind: RouteRule
  metadata:
    name: switch-to-blue
  spec:
    destination:
      name: helium-aks
    precedence: 1
    route:
    - labels:
        version: blue
      weight: 100
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tcp-echo
spec:
  hosts:
  - "*"
  gateways:
  - tcp-echo-gateway
  tcp:
  - match:
    - port: 31400
    route:
    - destination:
        host: tcp-echo
        port:
          number: 9000
        subset: v1
      weight: 80
    - destination:
        host: tcp-echo
        port:
          number: 9000
        subset: v2
      weight: 20
