prometheus:
  url: http://prometheus.istio-system.svc.cluster.local
  port: 9090

rules:
  custom:
  - seriesQuery: 'istio_requests_total{namespace!="",pod_name=~"helium.*"}'
    resources:
      overrides:
        namespace: {resource: "namespace"}
        pod_name: {resource: "pod"}
    name:
      matches: "^(.*)"
      as: "rps"
    metricsQuery: 'avg(rate(<<.Series>>{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>)'